                                         -- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 18:25:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema GatorMatorDB
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `GatorMartDB` ;

-- -----------------------------------------------------
-- Schema GatorMatorDB
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `GatorMartDB` DEFAULT CHARACTER SET utf8 ;
USE `GatorMartDB` ;


--ADD NAME AND USERNAME TO USER TABLE

-- -----------------------------------------------------
-- Table `GatorMatorDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GatorMartDB`.`User` ;

CREATE TABLE IF NOT EXISTS `GatorMartDB`.`User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(225) NOT NULL,
  `Password` VARCHAR(225) NOT NULL,
  `Bio_Description` VARCHAR(225) NOT NULL,
  `Phone_Number` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`User_ID`));


-- -----------------------------------------------------
-- Table `GatorMatorDB`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GatorMartDB`.`Post` ;

CREATE TABLE IF NOT EXISTS `GatorMartDB`.`Post` (
  `Post_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Title` VARCHAR(225) NOT NULL,
  `Category` VARCHAR(225) NOT NULL,
  `Available` INT NOT NULL,
  `Post_Description` VARCHAR(225) NOT NULL,
  `Price` FLOAT NOT NULL,
  `Type` VARCHAR(225) NOT NULL,
  `Direction` VARCHAR(225) NOT NULL,
  `File_Link` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Post_ID`));


-- -----------------------------------------------------
-- Table `GatorMatorDB`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GatorMartDB`.`Review` ;

CREATE TABLE IF NOT EXISTS `GatorMartDB`.`Review` (
  `Review_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Post_ID` INT NOT NULL,
  `Direction` VARCHAR(225) NOT NULL,
  `Review_Describtion` VARCHAR(225) NOT NULL,
  `Rating` INT NOT NULL,
PRIMARY KEY (`Review_ID`));


-- ---------------------------------------------------------------------------------------------------------- --
-- 								DATA INSERTS                                                                  --
-- ---------------------------------------------------------------------------------------------------------- --
  
INSERT INTO User (User_ID, Email, Password, Bio_Description, Phone_Number)
VALUES
(1, 'LShire1@mail.sfsu.edu', 'UniquePassword1', 'Just a senior at SFSU!', '(111) 111 - 1111'),
(2, 'IDunagan2@mail.sfsu.edu', 'UniquePassword2', 'Just a junior at SFSU!', '(222) 222 - 222'),
(3, 'CGresham3@mail.sfsu.edu', 'UniquePassword3', 'Just a sophomore at SFSU!', '(333) 333 - 3333'),
(4, 'NBriones4@mail.sfsu.edu', 'UniquePassword4', 'Just a freshman at SFSU!', '(444) 444 - 4444'),
(5, 'AGlover5@mail.sfsu.edu', 'UniquePassword5', 'Just a teacher at SFSU!', '(555) 555 - 5555'),
(6, 'LGriffin6@mail.sfsu.edu', 'UniquePassword6', 'Just a faculty member at SFSU!', '(666) 666 - 6666'),
(7, 'MMaurice7@mail.sfsu.edu', 'UniquePassword7', 'Just another senior at SFSU!', '(777) 777 - 7777'),
(8, 'AGomez8@mail.sfsu.edu', 'UniquePassword8', 'Just another junior at SFSU!', '(888) 888 - 8888'),
(9, 'RGuillotte9@mail.sfsu.edu', 'UniquePassword9', 'Just another sophomore at SFSU!', '(999) 999 - 9999'),
(10, 'LBrode10@mail.sfsu.edu', 'UniquePassword10', 'Just another freshman at SFSU!', '(000) 000 - 0000');

-- ---------------------------------------------------------------------------------------------------------- --
INSERT INTO Post (Post_ID, User_ID, Title, Category, Available, Post_Description, Price, Type, Direction, File_Link)
VALUES
(1, 1, 'Learning Life: The Path to Academic Success and Personal Happiness', 'Textbook', 1, 'For self improvement class, okay quality.', 20, 'product', 'providing', '../images/BookSelfImprove.jpg'),
(2, 2, 'Calculus: Early Transcendentals', 'Textbook', 1, 'For Calculus, it is slightly used..', 12, 'product', 'providing', '../images/BookCalculus.jpg'),
(3, 3, 'Physics for Scientists and Engineers: A Strategic Approach', 'Textbook', 1, 'For physics, it is used/damaged.', 5, 'product', 'providing', '../images/BookPhysics.jpg'),
(4, 4, 'Understanding and Using English Grammar', 'Textbook', 1, 'For English, it`s just like new!', 10, 'product', 'providing', '../images/BookEnglish.jpg'), 
(5, 5, 'CSC 648 Notes', 'Notes', 1, 'For Software Engineering, incredibly indepth!', 100, 'product', 'providing', '../images/NotesCSC648.jpg'),
(6, 6, 'CSC 665 Notes', 'Notes', 1, 'For Artifical Intelligence, not much written.', 5, 'product', 'providing', '../images/NotesCSC665.jpg'),
(7, 7, 'CSC 642 Notes', 'Notes', 1, 'For Human Computer Interaction, simple', 3, 'product', 'providing', '../images/NotesCSC642.jpg'),
(8, 8, 'Coffee Table', 'Furniture', 1, 'Slightly stained coffee table, no damage, need gone ASAP!', 7, 'product', 'providing', '../images/FurnitureTable.jpg'),
(9, 9, 'Computer Chair', 'Furniture', 1, 'Old computer chair; crusty, but comfortable!', 15, 'product', 'providing', '../images/FurnitureChair.jpg'),
(10, 10, 'Couch', 'Furniture', 1, 'Freshly bought couch, doesnt fit in my dorm!', 30, 'product', 'providing', '../images/FurnitureCouch.jpg');

-- ---------------------------------------------------------------------------------------------------------- --
SELECT * FROM GatorMartDB.User;
SELECT * FROM GatorMartDB.Post;
